### ISSUE TITLE
TypeError: read_vasp_out() got an unexpected keyword argument 'force_consistent'

### ISSUE THREAD

**Issue by sillycheng** [MDIL-SNU/SIMPLE-NN#64]
**This project is very helpful to me. But when I run the run.py script(I have installed tensorflow, mpi4py and run the setup.py), there is always show me this error,**

> WARNING:tensorflow:From C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\__init__.py:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.inputs = deep_update(self.inputs, yaml.load(input_file), warn_new_key=True,
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    model.run()
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\__init__.py", line 172, in run
    self.descriptor.generate()
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\features\symmetry_function\__init__.py", line 507, in generate
    snapshots = io.read(tmp_name, index=index, format=self.inputs['refdata_format'], force_consistent=True)
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\formats.py", line 495, in read
    **kwargs))
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\formats.py", line 556, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\formats.py", line 354, in wrap_read_function
    for atoms in read(filename, index, **kwargs):
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\utils\__init__.py", line 403, in iofunc
    obj = func(fd, *args, **kwargs)
TypeError: read_vasp_out() got an unexpected keyword argument 'force_consistent'

**I am not familiar with ase. And if i delete this option in the file"C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\features\symmetry_function\__init__.py", when I run this script again, it will show me another error :**

> WARNING:tensorflow:From C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\__init__.py:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.inputs = deep_update(self.inputs, yaml.load(input_file), warn_new_key=True,
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    model.run()
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\__init__.py", line 172, in run
    self.descriptor.generate()
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\simple_nn-0.9.0-py3.6-win-amd64.egg\simple_nn\features\symmetry_function\__init__.py", line 507, in generate
    snapshots = io.read(tmp_name, index=index, format=self.inputs['refdata_format'])
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\formats.py", line 495, in read
    **kwargs))
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\formats.py", line 556, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\formats.py", line 354, in wrap_read_function
    for atoms in read(filename, index, **kwargs):
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\utils\__init__.py", line 403, in iofunc
    obj = func(fd, *args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\vasp.py", line 515, in read_vasp_out
    return list(g)
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\utils.py", line 247, in __call__
    for chunk in self._getslice(fd, index):
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\vasp.py", line 477, in outcarchunks
    header_data = _read_outcar_header(fd)
  File "C:\Users\Administrator\Anaconda3\envs\tf\lib\site-packages\ase-3.18.0-py3.6.egg\ase\io\vasp.py", line 472, in _read_outcar_header
    raise IOError('Incomplete OUTCAR')
OSError: Incomplete OUTCAR

**How can I deal with these two problems?**

**Comment by JisuJung928** [comment]
Hello, sillycheng. We found that `ase` change `read_vasp_out` function in `3.18.0` update. In this update, `force_consistent` tag in `read_vasp_out` function is removed and that is the source of the first error. In the case of the second error, it might be originated from `compress_outcar: true` in `input.yaml` since the compressed version of `OUTCAR` is only available in `ase<=3.17.0`. Thus, both error can be solved for downgrading your `ase` module to version `3.17.0`. Or, you can use `compress_outcar: false` in `input.yaml` with `ase==3.18.0` instead of downgrading ase. If you still face the error after doing one of solution we suggest, please let me know and send the `OUTCAR` file if possible.

**Comment by sillycheng** [comment]
> Hello, sillycheng. We found that `ase` change `read_vasp_out` function in `3.18.0` update. In this update, `force_consistent` tag in `read_vasp_out` function is removed and that is the source of the first error. In the case of the second error, it might be originated from `compress_outcar: true` in `input.yaml` since the compressed version of `OUTCAR` is only available in `ase<=3.17.0`. Thus, both error can be solved for downgrading your `ase` module to version `3.17.0`. Or, you can use `compress_outcar: false` in `input.yaml` with `ase==3.18.0` instead of downgrading ase. If you still face the error after doing one of solution we suggest, please let me know and send the `OUTCAR` file if possible.

Thank you, I downgraded my ase module to version 3.17.0, then run the example, it works.

**Comment by vsumaria** [comment]
Does the program only read OUTCAR files as input? All my structures with energy and forces are stored in traj files and ase is unavailable to write convert the traj files into OUTCAR. 

Is there any way around this issue. Thanks

**Comment by will1792** [comment]
@vsumaria I think SIMPLE-NN can handle other formats that ase can read without any problem. You just need to tell the format in the `input.yaml` via `refdata_format` option under `symmetry_function`. For example:
```yaml
symmetry_function:
  refdata_format: traj
  (other options)
```
The default value for `refdata_format` is `vasp-out`. Refer https://wiki.fysik.dtu.dk/ase/ase/io/io.html for available file formats and their name.

**Comment by vsumaria** [comment]
That is amazing. I didn’t realize that was an option. Thanks !
